[project]
name = "four-letter-blocks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "colorspacious>=1.1.2",
    "crossword-generator>=0.2.2",
    "miniexact>=1.6.1",
    "pyside6>=6.11.2",
    "pyyaml>=6.0.3",
    "scipy>=1.18.1",
]

[dependency-groups]
dev = [
    "mypy>=2.4.0",
    "pytest>=9.1.1",
    "scipy-stubs>=1.18.1.1",
    "space-tracer>=4.13.0",
    "types-pyyaml>=6.0.12.20260906",
]

[[tool.mypy.overrides]]
module = ["miniexact.*"]
ignore_missing_imports = true
